### ISSUE TITLE
Scrape general league attributes 

### ISSUE THREAD

**Issue by dcaribou** [dcaribou/transfermarkt-scraper#22]
There are a few general league attributes in the league index page that would be rather easy to parse and expose in the 'leagues' crawler. This ticket is to parse those and expose the leagues crawler results

<img width="584" alt="Screenshot 2021-07-10 at 16 47 13" src="https://user-images.githubusercontent.com/16071835/125167060-dcc65580-e19e-11eb-801b-fd7655262b19.png">

**Comment by Nytrm** [comment]
`      total_clubs = row.xpath('td')[2].get()
      total_players = row.xpath('td')[3].get()
      average_age = row.xpath('td')[4].get()
      foreigner_percentage = row.xpath('td')[5].get()

      total_value = row.xpath('td')[7].get()`

just not sure how to get the actual content with xpath notation, some minor change but then this could be added.

**Comment by dcaribou** [comment]
That sounds like it should work, yes.

The notation to get the text content in xpath is `/text()`. For example:
https://github.com/dcaribou/transfermarkt-scraper/blob/4deb7c8f17790f12238fb68b116f26e0aa9c276d/tfmkt/spiders/games.py#L140

**Comment by Nytrm** [comment]
https://github.com/dcaribou/transfermarkt-scraper/pull/64

**Comment by Nytrm** [comment]
this could be closed as its merged in above pr

**Comment by dcaribou** [comment]
> this could be closed as its merged in above pr

You are right!
Closing.
