### ISSUE TITLE
Update scraping logic for "player data"

### ISSUE THREAD

**Issue by dcaribou** [dcaribou/transfermarkt-scraper#29]
There has been a change on transfermarkt side that is affecting the scraping of player attributes. The `players` scraper is currently returning no values for player attributes.

The change seems to have happened on the "player data" section, as the query `response.css('table.auflistung tr')` is currently returning no values.

**Comment by DonFloriano27** [comment]
The new html for the player data should be this one right? 
![Bildschirmfoto 2021-09-23 um 10 56 46](https://user-images.githubusercontent.com/90830651/134480440-8726be52-a652-4a46-b20f-51de875f652a.png)

As I understand the players scraper code creates a table with attributes and all data - one by one - is written in the attributes dict. Now they changed it to grid so we must adjust the code to grid type?

**Comment by dcaribou** [comment]
Hi @DonFloriano27. You are right, this is the new html code for the "player data" section in the players page, which is used to extract some of the player attributes. 

<img width="688" alt="Screenshot 2021-09-23 at 14 50 10" src="https://user-images.githubusercontent.com/16071835/134509647-5cc4d2f2-23fb-44c4-bbeb-a9fd7e93ec8f.png">

Before the change on transfermarkt this week the html was a bit different, and the raw attributes list could be obtained with the css query
https://github.com/dcaribou/transfermarkt-scraper/blob/8478d52d8a7da7b3ef3be3deb46e6c802bb0b7d8/tfmkt/spiders/players.py#L52

In order to parse the new html structure, I believe the query needs to be changed now to something like
```python
attributes_table  = response.css('div.player-data-personal-info span')
```
and the post-processing to fill in the `attributes` dict needs to be adjusted a bit.
