### ISSUE TITLE
Scraping historical player value

### ISSUE THREAD

**Issue by lukesonnet** [dcaribou/transfermarkt-scraper#37]
One of the most important functions of scraping the transfermarkt website, that I can see, is to build a historical panel of data on market values for players over time such that you can understand what a player's value was at the start of a season to avoid biased analysis (akin to, say, post-treatment bias).

How difficult do you think it would be to add the ability to scrape the table below the Player Data section on a player's page to get this time series?

**Comment by dcaribou** [comment]
Hey @lukesonnet, I've provided feedback on #38 some time ago, are you still interested in contributing this functionality?

Thanks again for work here.

**Comment by dcaribou** [comment]
Closed by #43
