### ISSUE TITLE
Contract Expiring

### ISSUE THREAD

**Issue by siddhanuka** [dcaribou/transfermarkt-scraper#45]
We can add the contract expiry date along with the player_valuation file, which will give another dimension of problem statement to be answered to the dataset. I propose this as an enhancement to extend the scraper.

![image](https://user-images.githubusercontent.com/26890694/195974184-0e06a48b-1300-47b3-8d5f-4b6053dd33ec.png)

**Comment by dcaribou** [comment]
@siddhanuka, the contract expiration per player is already being scraped. Check this line
https://github.com/dcaribou/transfermarkt-scraper/blob/25620ce7e746da012e6339885e57132c92a72771/tfmkt/spiders/players.py#L80
This represents the expiration date for the current contract of each players (i.e, if a player changes contract, this value would change too). If this works for you, I can have it published to the dataset (`players` file)
