### ISSUE TITLE
Dušan Vlahović's name being listed incorrectly / Scraper incorrectly handling š symbols

### ISSUE THREAD

**Issue by tvqt** [dcaribou/transfermarkt-scraper#46]
Hi there,

I was going through the data earlier, and I noticed Dušan Vlahović was being listed as "Du Scaron An Vlahović". On further investigation, that is how his name is written in [his Transfermarkt URL](https://www.transfermarkt.com/du-scaron-an-vlahovi%C4%87/profil/spieler/357498), and the š symbol is known as [a caron](https://en.wikipedia.org/wiki/Caron#In_Balto-Slavic_languages)

**Comment by dcaribou** [comment]
FYI @tvqt 

With [this PR](https://github.com/dcaribou/transfermarkt-scraper/pull/56) we should ve ready to solve this problem in the [dataset repo](https://github.com/dcaribou/transfermarkt-datasets). I'm moving the issue there.
* https://github.com/dcaribou/transfermarkt-datasets/issues/128
