### ISSUE TITLE
First name // Last name in different columns

### ISSUE THREAD

**Issue by tvqt** [dcaribou/transfermarkt-scraper#47]
Hi again, 

I've noticed that Transfermarkt formats first name and last names differently in their pages- last names are given the "strong" tag, whereas first names are not:
<img width="453" alt="Screenshot 2022-12-15 at 12 27 41 am" src="https://user-images.githubusercontent.com/12098500/207570934-b62db823-b6c4-42ab-958d-b60906142001.png">

<img width="357" alt="Screenshot 2022-12-15 at 12 31 08 am" src="https://user-images.githubusercontent.com/12098500/207571636-f7e3155d-d41b-4125-b30c-60ff42026c23.png">

It would be great to gather these, for a number of reasons: 
1. It's tidier to separate out the two variables (first name, last name) into different columns
2. as the examples above illustrate, it's not always clear where the first name(s) end and the last name(s) start
3. names sometimes contain dashes, which seem to be missed by the current approach

**Comment by dcaribou** [comment]
Great idea @tvqt!

I totally agree that the logic to get the player name has a lot of room for improvement, as it currently is purely URL based. This is actually also the root cause of #46.

**Comment by dcaribou** [comment]
I've helped people with installation problems in a [couple of issues](https://github.com/dcaribou/transfermarkt-scraper/issues?q=is%3Aissue+is%3Aclosed+label%3Ainstallation). Perhaps those would'd been be helpful.
One common problem is forgetting to set the `USER_AGENT` parameter, for example.
<img width="852" alt="image" src="https://user-images.githubusercontent.com/16071835/208086608-7294962f-39f1-41f4-9b9d-17e2c53f19bc.png">

Anyways, if you are more confortable with R, then you should totally go with that. Thanks for sharing the code.

**Comment by tvqt** [comment]
> One common problem is forgetting to set the `USER_AGENT` parameter, for example
I totally missed this 🤦‍♂️ it is working now- thanks so much for your help!

I added a pull request to clarify this (unsure if there's a way to get scrapy to remember the user agent token, but if not, it makes sense to add it to the examples, as they wouldn't run without the tokens
https://github.com/dcaribou/transfermarkt-scraper/pull/48#issue-1500138191

**Comment by dcaribou** [comment]
FYI @tvqt 

With [this PR](https://github.com/dcaribou/transfermarkt-scraper/pull/56) we should ve ready to solve this problem in the [dataset repo](https://github.com/dcaribou/transfermarkt-datasets). I'm moving the issue there.
* https://github.com/dcaribou/transfermarkt-datasets/issues/129
