### ISSUE TITLE
Appearances 

### ISSUE THREAD

**Issue by AzF01** [dcaribou/transfermarkt-scraper#53]
Is it possible to use this package to obtain appearances (e.g. in Champions League and International Appearances), for a select group of players? (e.g. all Premier League players)

**Comment by dcaribou** [comment]
Hi @AzF01.
Yes, this is exactly what the `appearances` crawler is about. The project README has instructions for setting up your environment to run it, if you want to give it a try.

For convenience, I've pre scraped a bunch of that using this scraper in the [transfermarkt-datasets](https://github.com/dcaribou/transfermarkt-datasets) project, appearances included. That might be enough for your purpose. Check it out.

<img width="1349" alt="image" src="https://user-images.githubusercontent.com/16071835/209427651-1186d278-fb89-49cb-be77-35a01b0e54df.png">

**Comment by dcaribou** [comment]
Not enough information. Closing.
