### ISSUE TITLE
Scrape starting lineup from games page

### ISSUE THREAD

**Issue by dcaribou** [dcaribou/transfermarkt-scraper#59]
The [games page](https://www.transfermarkt.co.uk/metalurg-zaporizhya-2016-_goverla-uzhgorod-2016-/index/spielbericht/2477955) contains the starting lineup information for each team. This seams to be the most accurate source for extracting this data, as using game events to reconstruct line ups has limitations.

The games crawler can be modified to extract this data.

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/16071835/211189704-f5d42f0f-0a7a-4c3d-8b31-2d7d4a865b73.png">

**Comment by Nytrm** [comment]
Might be better to target [this page ](https://www.transfermarkt.co.uk/arsenal-fc_manchester-united/aufstellung/spielbericht/3838781) because it gives a better table to scrape.
