### ISSUE TITLE
Scrapy checks failing `parse_competitions`

### ISSUE THREAD

**Issue by dcaribou** [dcaribou/transfermarkt-scraper#60]
_scrapy.exceptions.ContractFail: Returned 3 items, expected 2_

Full error log [here](https://github.com/dcaribou/transfermarkt-scraper/actions/runs/3908326572/jobs/6678380234).

**Comment by Nytrm** [comment]
i think this is resolved right?

**Comment by dcaribou** [comment]
That's right @Nytrm, it was resolved in [this](https://github.com/dcaribou/transfermarkt-scraper/pull/62/files#diff-4996e11a876c85217375d188a4a6bc165f0c39b824ac597a991c0f3da222644e) recent PR.
Closing.
