### ISSUE TITLE
players.py xpath expression to get list url of players is not correct anymore

### ISSUE THREAD

**Issue by n-richaud** [dcaribou/transfermarkt-scraper#68]
Hi , i tried today your scrapper and when scrapping player , i had empty json.
After debugging it seems the structure of club page has changed and the xpath expression is wrong ,
the correct one is `//table[@class="inline-table"]/tr[1]/td[2]/a/@href` .
I didn't do a PR because while debugging i found that the first tr element of the table have a data-link class and a data-link attributes with the url. Extracting url from this attributes could be more reliable ? Or we can implement a fallback ?

**Comment by dcaribou** [comment]
Hi @n-richaud.
Thanks for pointing this out. This seems to be the reason why [tests are failing](https://github.com/dcaribou/transfermarkt-scraper/actions/runs/5940765562/job/16110067106) indeed.

**Comment by dcaribou** [comment]
The linked PR I've just merged should fix it. Thanks for the tip on the improved xpath.

Feel free to submit your own PR next time 😄
