### ISSUE TITLE
Scrapy crawl creates empty .json files

### ISSUE THREAD

**Issue by BCinformational** [dcaribou/transfermarkt-scraper#87]
After following the instructions up until that point, both of these commands only create empty .json files with no errors. Is this intentional or am I misunderstanding something?

scrapy crawl confederations > confederations.json
scrapy crawl competitions -a parents=confederations.json > competitions.json

**Comment by dcaribou** [comment]
Hey @BCinformational. Similar issues were reported [here](https://github.com/dcaribou/transfermarkt-scraper/issues/74) and [here](https://github.com/dcaribou/transfermarkt-scraper/issues/30).
Could you kindly try those suggestions and follow-up in any of those other issues if you can't figure it out?
